services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: scheduler-backend
    ports:
      - "443:443"
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - scheduler-net
    volumes:
      - /etc/letsencrypt/live/scheduler.pl:/ssl:ro

  db:
    image: postgres:16
    container_name: scheduler-db
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - scheduler-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  frontend:
    build: ./frontend
    container_name: scheduler-frontend
    ports:
      - "4200:80"
    networks:
      - scheduler-net
    depends_on:
      - backend

networks:
  scheduler-net:
    driver: bridge

volumes:
  pgdata:
